### ISSUE TITLE
bmiidx7 video is not working

### ISSUE THREAD

**Issue by Marsoff9898** [987123879113/mame#12]
### MAME version

0.265

### System information

Windows 11
AMD Ryzen 7 Pro 4750G
AMD Radeon 6700 XT
Adrenaline Driver 24.5.1
Video: auto

### Incorrect behaviour

IIDX 7th Style ain't showing the videos, it its just black screen.

### Expected behaviour

It should read videos from videos_iidx/b44jaa02

### Additional details

The problem lies on the (GCB44 JAB), it did work if I selected the version (GCB44 JAA).

**Comment by 987123879113** [comment]
Not a bug. JAB was an upgrade kit that changed the DVD player to use the XV-S1100 DVD player by default. Change the DVD player type in the operator menu from XV-S1100 to XV-D701 (I verified that it does work in-game if you change the DVD player type just now) or just use JAA.

**Comment by 987123879113** [comment]
I edited the wiki page to include a note about that to make it clearer: https://github.com/987123879113/mame/wiki/beatmania-IIDX

The same applies to IIDX 8th style.
