### ISSUE TITLE
iidxs and iidxsa dvd error

### ISSUE THREAD

**Issue by BokMeow** [987123879113/mame#14]
### MAME version

mame-windows-gcc-8da0fe3ae9378244c557bb389673a336f21b6fd3

### System information

Windows 11, AMD X5950, US/ENG

### Emulated system/software

twinkle.cpp

### Incorrect behaviour

all other twinkle.cpp titles  work fine not sure how to clean the config for this system.

### Expected behaviour

cannot continue DVD error

**Comment by 987123879113** [comment]
I just tested with the latest bemani branch and it's working fine, so the issue is somewhere on your end. Try using the latest build (see Wiki for links) and/or delete your nvram/bmiidxs and nvram/bmiidxsa folders, and maybe even cfg/bmiidxs.cfg and cfg/bmiidxsa.cfg config files.

**Comment by BokMeow** [comment]
ok yea will try that just needed ideas to clean up cached entries for other mame versions

**Comment by BokMeow** [comment]
well clearing all that and the nvram for gc863 had to clear backup ram again but still DVD error. Is there any other profile data or hidden cache items for mame that this could be reading from?. All the other twikle.cpp titles works flawless. not sure where it would be getting the dvd driver from.

**Comment by 987123879113** [comment]
No. The only thing I can suggest at this point is to make sure you're using the latest version (the version shown in your first post is not the latest version) and clear your nvram entirely. The games work fine on my end so I don't have any ideas besides that.

**Comment by BokMeow** [comment]
that fixed both my problems thanks!
