### ISSUE TITLE
bmiidx8 video isnt working

### ISSUE THREAD

**Issue by hoholee12** [987123879113/mame#2]
### MAME version

0.251

### System information

windows 10 22h2
i5-9400f
16gb ram
gtx1660

&

windows 10 22h2
i5-1135g7
16gb ram
mx450

### Incorrect behaviour

every other iidx versions work fine with your video mod.
except 8th style. its just black screen.
i tried watching with procexp and it doesnt seem to read any video files.

### Expected behaviour

read video files from videos_iidx/c44jaa02

**Comment by hoholee12** [comment]
NVM. dvd settings was the reason it didnt work. you have to go into the test mode and change dvd to xvd701 and reboot it.

**Comment by Marsoff9898** [comment]
You mean 7th Style?
